### get all appointents
GET http://127.0.0.1:5001/api/appointmentTypes

### get test by appointment id
GET http://127.0.0.1:5001/api/appointmentTypes/Consultation


### create test  /// Check-up
POST http://localhost:5001/api/appointmentTypes
Content-Type: application/json

{
    "name": "Consultation" 
}

### update test
PUT http://localhost:5001/api/appointmentTypes/Consultation
Content-Type: application/json

{
    "available":"true"
}

### delete test
DELETE http://localhost:5001/api/appointmentTypes/Consultation

